# https://developers.cloudflare.com/pages/functions/wrangler-configuration/
name = "neos21"
compatibility_date = "2024-09-17"
pages_build_output_dir = "."

[[d1_databases]]
database_id = "596021cd-b16c-46c2-a4c0-998f0b60b055"
binding = "DB"
database_name = "neos21"

[[env.production.d1_databases]]
database_id = "596021cd-b16c-46c2-a4c0-998f0b60b055"
binding = "DB"
database_name = "neos21"
